// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "kutego-api",
    "version": "0.1.0"
  },
  "paths": {
    "/cat/random": {
      "get": {
        "description": "Return a random Cat Image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Size for your Cat ('x-small','small','medium')",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a random cat.",
            "schema": {
              "type": "file"
            }
          },
          "400": {
            "description": "there is something wrong in the path."
          }
        }
      }
    },
    "/cat/{name}": {
      "get": {
        "description": "Return the Cat Image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "The name of the Cat to display.",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Size for your Cat",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the cat.",
            "schema": {
              "type": "file"
            }
          },
          "400": {
            "description": "Invalid characters in \"name\" were provided."
          }
        }
      }
    },
    "/cats": {
      "get": {
        "description": "List all the cat",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Cat name",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Return the Cats list.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cat"
              }
            }
          }
        }
      }
    },
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cat": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "my-cat"
        },
        "path": {
          "type": "string",
          "example": "my-cat.gif"
        },
        "url": {
          "type": "string",
          "example": "https://raw.githubusercontent.com/Pandahoro/cats/main/arrow-cat.gif"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition",
    "title": "kutego-api",
    "version": "0.1.0"
  },
  "paths": {
    "/cat/random": {
      "get": {
        "description": "Return a random Cat Image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Size for your Cat ('x-small','small','medium')",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a random cat.",
            "schema": {
              "type": "file"
            }
          },
          "400": {
            "description": "there is something wrong in the path."
          }
        }
      }
    },
    "/cat/{name}": {
      "get": {
        "description": "Return the Cat Image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "The name of the Cat to display.",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Size for your Cat",
            "name": "size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the cat.",
            "schema": {
              "type": "file"
            }
          },
          "400": {
            "description": "Invalid characters in \"name\" were provided."
          }
        }
      }
    },
    "/cats": {
      "get": {
        "description": "List all the cat",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Cat name",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Return the Cats list.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Cat"
              }
            }
          }
        }
      }
    },
    "/healthz": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Cat": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "my-cat"
        },
        "path": {
          "type": "string",
          "example": "my-cat.gif"
        },
        "url": {
          "type": "string",
          "example": "https://raw.githubusercontent.com/Pandahoro/cats/main/arrow-cat.gif"
        }
      }
    }
  }
}`))
}
