// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Pandahoro/kutego-api/pkg/swagger/server/models"
)

// GetCatsOKCode is the HTTP code returned for type GetCatsOK
const GetCatsOKCode int = 200

/*GetCatsOK Return the Cats list.

swagger:response getCatsOK
*/
type GetCatsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Cat `json:"body,omitempty"`
}

// NewGetCatsOK creates GetCatsOK with default headers values
func NewGetCatsOK() *GetCatsOK {

	return &GetCatsOK{}
}

// WithPayload adds the payload to the get cats o k response
func (o *GetCatsOK) WithPayload(payload []*models.Cat) *GetCatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cats o k response
func (o *GetCatsOK) SetPayload(payload []*models.Cat) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Cat, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
