// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCatRandomOKCode is the HTTP code returned for type GetCatRandomOK
const GetCatRandomOKCode int = 200

/*GetCatRandomOK Returns a random cat.

swagger:response getCatRandomOK
*/
type GetCatRandomOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetCatRandomOK creates GetCatRandomOK with default headers values
func NewGetCatRandomOK() *GetCatRandomOK {

	return &GetCatRandomOK{}
}

// WithPayload adds the payload to the get cat random o k response
func (o *GetCatRandomOK) WithPayload(payload io.ReadCloser) *GetCatRandomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cat random o k response
func (o *GetCatRandomOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCatRandomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCatRandomBadRequestCode is the HTTP code returned for type GetCatRandomBadRequest
const GetCatRandomBadRequestCode int = 400

/*GetCatRandomBadRequest there is something wrong in the path.

swagger:response getCatRandomBadRequest
*/
type GetCatRandomBadRequest struct {
}

// NewGetCatRandomBadRequest creates GetCatRandomBadRequest with default headers values
func NewGetCatRandomBadRequest() *GetCatRandomBadRequest {

	return &GetCatRandomBadRequest{}
}

// WriteResponse to the client
func (o *GetCatRandomBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
